services:
  frontend:
    build:
      context: ./next-app
      dockerfile: ./DockerFile
    volumes:
      - ./next-app:/usr/src/next-app
      - /next-app/node_modules
    ports:
      - '3002:3002'
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    tty: true

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: